version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: honeycomb
      POSTGRES_USER: honeycomb
      POSTGRES_PASSWORD: honeycomb
    ports:
      - "5432:5432"
