version: "3.9"
services:
  honeycomb-app-1:
    build:
      context: ../..
      dockerfile: Example/honeycomb-example/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    expose:
      - "8080"
      - "9091"
      - "9092"
      - "9093"
    depends_on:
      - redis
      - postgres
  honeycomb-app-2:
    build:
      context: ../..
      dockerfile: Example/honeycomb-example/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    expose:
      - "8080"
      - "9091"
      - "9092"
      - "9093"
    depends_on:
      - redis
      - postgres
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - honeycomb-app-1
      - honeycomb-app-2
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: honeycomb
      POSTGRES_USER: honeycomb
      POSTGRES_PASSWORD: honeycomb
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    depends_on:
      - honeycomb-app-1
      - honeycomb-app-2
